services:
  database:
    image: mysql:8.0
    container_name: db-gmu
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gmu
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - gmu-net
    volumes:
      - gmu-data:/var/lib/mysql

  frontend:
    image: client:gmu-v1
    container_name: fe-gmu
    build:
      context: ./gmu-front
    ports:
      - "80:80"
    networks:
      - gmu-net

  backend:
    image: services:gmu-v1
    container_name: be-gmu
    build:
      context: ./gmu-back
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/gmu
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: R01VLVBSMFkzQzctU1Q0TVAtMGM1MmZiZDgtMGYxYS00MzliLTkyYWYtMjc4NDYzNzAwNzI4
    ports:
      - "8081:8080"
    networks:
      - gmu-net
    depends_on:
      - database

networks:
  gmu-net:
    driver: bridge

volumes:
  gmu-data:
    driver: local